---
title: "Resources for global sustainability"
description: |
  A compendium
author:
  - name: shikokuchuo
date: 05-02-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r index, echo=FALSE}

photos <- file.path("_images", list.files("_images"))
develop <- function(x) {
  plot(imager::load.image(x), axes = FALSE)
  paste0(openssl::sha256(file(x)))
}
par(mar = c(0, 0, 0, 0))
data.frame(sha256 = do.call(rbind, lapply(photos, develop)))

```
<aside> Dawn over Shikokuchuo </aside>

### Stockholm Resilience Center

Sustainability science for biosphere stewardship, Stockholm University

Video: Our future in the Anthropocene biosphere

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/5pAONwIKor8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### The National Academies of Sciences, Engineering, and Medicine

Nobel Prize Laureates and Other Experts Issue Urgent Call for Action After ‘Our Planet, Our Future’ Summit

https://www.nationalacademies.org/news/2021/04/nobel-prize-laureates-and-other-experts-issue-urgent-call-for-action-after-our-planet-our-future-summit

### BBC

Greta Thunberg: A Year to change the World

https://bbc.co.uk/ayeartochangetheworld

### Coursera

Solving Complex Problems Specialization - uses the framework of Big History to combine knowledge across the sciences and humanities to provide a foundation for thinking and research in new ways. One of the creators of the course, Professor David Christian, has presented on topics including "Interdisciplinary Approaches to Solving 21st Century Challenges" at the World Economic Forum (WEF).

https://www.coursera.org/specializations/solving-complex-problems

### TED

Stephen Hawking, "Questioning the universe", TED February 2008

<div style="max-width:854px"><div style="position:relative;height:0;padding-bottom:56.25%"><iframe src="https://embed.ted.com/talks/lang/en/stephen_hawking_questioning_the_universe" width="854" height="480" style="position:absolute;left:0;top:0;width:100%;height:100%" frameborder="0" scrolling="no" allowfullscreen></iframe></div></div>

<aside>
Transcript: 09:06 | 
Stephen Hawking: I think it quite likely that we are the only civilization within several hundred light years; otherwise we would have heard radio waves. **The alternative is that civilizations don't last very long, but destroy themselves**.
</aside>
