---
title: "Datasets"
description: |
  For Econometrics and Machine Learning
author:
  - name: shikokuchuo
date: 05-05-2021
categories:
  - Resources
  - Data
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r index, echo=FALSE}

photos <- file.path("_images", list.files("_images"))
par(mar = c(0, 0, 0, 0))
plot(imager::load.image(photos), axes = FALSE)

```
<aside>Shikokuchuo</aside>

### Datasets

```{r table, echo=TRUE, layout="l-body-outset"}

library(magrittr)
tibble::tribble(
  ~Source, ~URL, ~Package,
  "Fred", "https://fred.stlouisfed.org/", "Quantmod",
  "Quandl", "https://www.quandl.com/", "Quandl",
  "Yahoo Finance", "https://finance.yahoo.com/", "Quantmod",
  "Damodaran NYU Stern", "http://people.stern.nyu.edu/adamodar/New_Home_Page/datacurrent.html", "",
  "UCI Machine Learning Repository", "https://archive.ics.uci.edu/ml/index.php", "",
  "Project Gutenberg", "https://www.gutenberg.org/", "gutenbergr"
) %>%
  dplyr::mutate(URL = purrr::map_chr(URL, ~paste0("<a href='", .x, "'>", .x, "</a>"))) %>%
  DT::datatable(escape = FALSE)

```


