---
title: "Resources for learning"
description: |
  A curated selection of online MOOCs
author:
  - name: shikokuchuo
date: 05-14-2021
categories:
  - Resources
  - Learning
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r index, echo=FALSE}

photos <- file.path("_images", list.files("_images"))
develop <- function(x) {
  plot(imager::load.image(x), axes = FALSE)
  paste0(openssl::sha256(file(x)))
}
par(mar = c(0, 0, 0, 0))
data.frame(sha256 = develop(photos))

```
<aside> Shikokuchuo <br />
Iyo Mishima station</aside>

### Coursera Specializations

```{r table, echo=TRUE, layout="l-body-outset"}

library(magrittr)
tibble::tribble(
  ~Institution, ~`Course or Specialization`, ~URL,
  "Duke University", "Statistics with R", "https://www.coursera.org/specializations/statistics",
  "Duke University", "Entrepreneurial Finance: Strategy and Innovation", "https://www.coursera.org/specializations/entrepreneurial-finance",
  "John Hopkins University", "Mastering Software Development in R", "https://www.coursera.org/specializations/r",
  "Sung Kyun Kwan University", "The Fundamentals of Data Driven Investment" ,"https://www.coursera.org/learn/the-fundamental-of-data-driven-investment"
) %>%
  dplyr::mutate(URL = purrr::map_chr(URL, ~paste0("<a href='", .x, "'>", .x, "</a>"))) %>%
  DT::datatable(escape = FALSE)

```



